# Generated by Django 4.2.1 on 2023-05-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='\\media'),
        ),
        migrations.AlterField(
            model_name='release',
            name='artist_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='release',
            name='song_name',
            field=models.CharField(max_length=200),
        ),
    ]
