# Generated by Django 4.2.1 on 2023-05-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_release_audio_file_alter_release_artist_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('audio_link', models.FileField(blank=True, max_length=200, null=True, upload_to='')),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='release',
        ),
    ]
