# Generated by Django 4.2.1 on 2023-05-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_playlist_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='play_image',
            field=models.ImageField(blank=True, null=True, upload_to='sng/'),
        ),
    ]
