# Generated by Django 4.2.1 on 2023-05-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_song_is_favorite_song_favorited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='favorited_by',
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.song')),
            ],
        ),
    ]
