# Generated by Django 4.2.1 on 2023-05-27 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
