# Generated by Django 4.2.1 on 2023-05-28 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_remove_song_favorited_by_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
