# Generated by Django 4.2.1 on 2023-05-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_song_favourites_delete_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=50)),
                ('artist_image', models.ImageField(blank=True, null=True, upload_to='Artist/')),
            ],
        ),
    ]
