# Generated by Django 4.2.1 on 2023-06-04 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist_name',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='app.artist'),
        ),
    ]
