# Generated by Django 4.2.1 on 2023-06-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_song_artist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist_name',
            new_name='artist',
        ),
    ]
