# Generated by Django 4.2.1 on 2023-06-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_artist_artist_name_remove_song_artist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artists_name',
            new_name='artist_name',
        ),
    ]
