# Generated by Django 4.2.1 on 2023-06-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_artists_name_artist_artist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_name',
            new_name='art_name',
        ),
    ]
