# Generated by Django 4.2.1 on 2023-06-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_artist_name_artist_art_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='art_name',
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
