# Generated by Django 4.2.1 on 2023-06-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
