# Generated by Django 4.2.1 on 2023-06-17 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_comments_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.playlist')),
            ],
        ),
    ]
