# Generated by Django 4.2.1 on 2023-06-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_createplaylist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createplaylist',
            old_name='playlist',
            new_name='playlistname',
        ),
    ]
