# Generated by Django 4.2.1 on 2023-06-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_createplaylist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createplaylist',
            name='playlistname',
        ),
        migrations.AddField(
            model_name='createplaylist',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
