# Generated by Django 4.2.1 on 2023-06-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_song_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='create',
        ),
        migrations.AddField(
            model_name='createplaylist',
            name='songs',
            field=models.ManyToManyField(to='app.song'),
        ),
    ]
