# Generated by Django 4.2.1 on 2023-06-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_song_create_createplaylist_songs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatePlaylist',
        ),
    ]
